services:
  web:
    image: node:20-alpine
    command: >
      sh -c "
      apk add --no-cache git &&
      rm -rf /app &&
      git clone https://github.com/ETdoFresh/DocumentExtractor.git /app &&
      cd /app &&
      npm install &&
      npm run build &&
      npm start"
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080"

networks:
  traefik-net:
    external: true
